# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(username: 'demo', password: 'demodemo', email: 'demo@demo.com')
Genre.create(title: 'Action', description: 'Shooting, fighting and more...')
Watchlist.create(title: 'demo watchlist', description: 'Demo description for watchlist', user_id: 1)
TvSeries.create(title: 'Spartacus', description: 'The life of Spartacus, the gladiator who lead a rebellion against the Romans. From his time as an ally of the Romans, to his betrayal and becoming a gladiator, to the rebellion he leads and its ultimate outcome.', release_date: 'January 22, 2010', image_url: 'https://occ-0-2774-2773.1.nflxso.net/dnm/api/v6/X194eJsgWBDE2aQbaNdmCXGUP-Y/AAAABfIfmWse-6EgKBTXG4a2EO-_zMtUpWQOqN_e1-P2p-xzzT8eLmyWXEGmhva31xgcSBTxHQog9uJ3bMh8kQLUgtkd64Y.webp?r=641')
Movie.create(title: 'Spartacus', description: 'The life of Spartacus, the gladiator who lead a rebellion against the Romans. From his time as an ally of the Romans, to his betrayal and becoming a gladiator, to the rebellion he leads and its ultimate outcome.', release_date: 'January 22, 2010', image_url: 'https://occ-0-2774-2773.1.nflxso.net/dnm/api/v6/X194eJsgWBDE2aQbaNdmCXGUP-Y/AAAABfIfmWse-6EgKBTXG4a2EO-_zMtUpWQOqN_e1-P2p-xzzT8eLmyWXEGmhva31xgcSBTxHQog9uJ3bMh8kQLUgtkd64Y.webp?r=641',video_url: 'https://youtu.be/eJiBouML3FQ', watchlist_id: 1)
Movie.create(title: 'The Red Serpent', description: "Spartacus, a free man of Thrace, agrees to join the Romans to battle his tribe's enemies. A betrayal sends his life spinning out of control.", release_date: 'January 22, 2010',tv_series_id: 1, image_url: 'https://m.media-amazon.com/images/M/MV5BOTcwMjAyMDI0NF5BMl5BanBnXkFtZTcwNzQzNzMxMw@@._V1_UY268_CR110,0,182,268_AL_.jpg', video_url: 'https://youtu.be/eJiBouML3FQ')
Movie.create(title: 'Stranger Things', description: "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.", release_date: '2019', image_url: 'https://occ-0-2774-2773.1.nflxso.net/dnm/api/v6/X194eJsgWBDE2aQbaNdmCXGUP-Y/AAAABbAJGyjtN3VkGy6a2beSc8L2CyeHN30fMbyeViVew8cVGmbJMPQojMt6zcrNjnKrTaziFlhTeQNcoDuwWRnMpBy0DvnIiQoLG07zdmUOeXA0jpC-fe8VK3QJBRGe.jpg?r=b4e', video_url: 'https://youtu.be/eJiBouML3FQ')
Movie.create(title: 'Money Heist', description: "Eight thieves take hostages and lock themselves in the Royal Mint of Spain as a criminal mastermind manipulates the police to carry out his plan.", release_date: '2019', image_url: 'https://occ-0-2774-2773.1.nflxso.net/dnm/api/v6/X194eJsgWBDE2aQbaNdmCXGUP-Y/AAAABYz1MPh7NPoE55666ZwBjo9vH2dtbGXo908Vy_ZXtwNGGx0OdJpTL0amDiWGwOvs9KNkr9cHHATKsuAvG8r3y-lNfM5Gq5XmFweQLfX2HK_bwL8zWyaCXf7t7KwJ.jpg?r=50f', video_url: 'https://youtu.be/eJiBouML3FQ')
Movie.create(title: 'Old Guard', description: "Ancient warriors, living in the shadows, fighting for what's right. But immortality can grow old — and nothing lasts forever.", release_date: '2019', image_url: 'https://occ-0-2774-2773.1.nflxso.net/dnm/api/v6/X194eJsgWBDE2aQbaNdmCXGUP-Y/AAAABccdNJhrfpWzHB1PMzEg27DVeqg7ub3q07HxWfA5rVWsONXmY9tcp3BA2vwwVjS0XMiWR3h_GzzDoD4ThAATMbU4f5fQekIfWLdgjXztnkeMaDIiRh1g0zZwEdwm.jpg?r=c52', video_url: 'https://youtu.be/eJiBouML3FQ')
Movie.create(title: 'Vikings', description: "King Bjorn reluctantly considers a plea from King Harald for military assistance. Ivar is shocked as Prince Oleg of Kiev makes a violent power grab.", release_date: '2019', image_url: 'https://occ-0-2774-2773.1.nflxso.net/dnm/api/v6/X194eJsgWBDE2aQbaNdmCXGUP-Y/AAAABYVZbqz_uitE0A1OmhKLo3WWuKlxVcPkV9Iaa2jtC-3OBvD1S8h27ov27K2A5e1Gvpt8TYTMPIroq_UtCn28Ho8rIxg.webp?r=eab', video_url: 'https://youtu.be/eJiBouML3FQ')
Movie.create(title: 'The Witcher', description: "Geralt of Rivia, a mutated monster-hunter for hire, journeys toward his destiny in a turbulent world where people often prove more wicked than beasts.", release_date: '2019', image_url: 'https://occ-0-2774-2773.1.nflxso.net/dnm/api/v6/X194eJsgWBDE2aQbaNdmCXGUP-Y/AAAABelflbF7hLllQWMP9vusyHxWklYqi-_xMHvad3rT2_mVkUWZoD_C1iDbNUCeeZ92dfng-rikd9HvJIUvZZ3oo32fhhKlwEdPt1CyR3cT7occykhrEeKHaHJglR78.jpg?r=382', video_url: 'https://youtu.be/eJiBouML3FQ')
Movie.create(title: 'Peaky Blinders', description: "A notorious gang in 1919 Birmingham, England, is led by the fierce Tommy Shelby, a crime boss set on moving up in the world no matter the cost.", release_date: '2019', image_url: 'https://occ-0-2774-2773.1.nflxso.net/dnm/api/v6/X194eJsgWBDE2aQbaNdmCXGUP-Y/AAAABZvbw253rjdf-lDxQgElGKjKa38YquVLfdyRu6L3XZnaunq4Inc5LXyH_KBfD6d7esLp09zMYWv_LvCFygghMWzB_LFiIxGr2tlSW5vMo97FUcZTe9BXBs7s_P-S.jpg?r=c25', video_url: 'https://youtu.be/eJiBouML3FQ')
Movie.create(title: 'Lucifer', description: "Bored with being the Lord of Hell, the devil relocates to Los Angeles, where he opens a nightclub and forms a connection with a homicide detective.", release_date: '2019', image_url: 'https://occ-0-2774-2773.1.nflxso.net/dnm/api/v6/X194eJsgWBDE2aQbaNdmCXGUP-Y/AAAABY4Xa-N3i4bkyZHHhx1flMX0yYdA1d9mLvD1i_TSdpaBh70ecOdls308UzojG3eNirEo4sXXLzcaX9Dweb8KaufQ-_xta9qyWD3pmE30dSlDO4hzdBacOjp0G9i7.jpg?r=62e', video_url: 'https://youtu.be/eJiBouML3FQ')
